# Generated by Django 6.0.7 on 2026-07-28 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Masculino'), ('Female', 'Femenino')], max_length=10, verbose_name='Género')),
                ('married', models.CharField(choices=[('Yes', 'Casado(a)'), ('No', 'Soltero(a)')], max_length=3, verbose_name='Estado Civil')),
                ('education', models.CharField(choices=[('Graduate', 'Graduado'), ('Not Graduate', 'No Graduado')], max_length=20, verbose_name='Nivel Educativo')),
                ('loan_status', models.CharField(default='Pendiente', max_length=20, verbose_name='Estado del Préstamo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
