# Generated by Django 6.0.7 on 2026-07-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprestamo',
            name='applicant_income',
            field=models.IntegerField(default=0, verbose_name='Ingreso del Solicitante'),
        ),
        migrations.AddField(
            model_name='solicitudprestamo',
            name='coapplicant_income',
            field=models.FloatField(default=0.0, verbose_name='Ingreso del Co-solicitante'),
        ),
        migrations.AddField(
            model_name='solicitudprestamo',
            name='credit_history',
            field=models.IntegerField(choices=[(1, 'Buen historial (Sin deudas pendientes)'), (0, 'Malo o sin historial crediticio')], default=1, verbose_name='Historial Crediticio'),
        ),
        migrations.AddField(
            model_name='solicitudprestamo',
            name='loan_amount',
            field=models.IntegerField(default=0, verbose_name='Monto del Préstamo (en miles)'),
        ),
    ]
